(async function () {
    try{

    } catch (e) {
      console.log('our error', e);
    }  
})();